out_dir: results
metric_best: f1
wandb:
  use: False
  project: code2
dataset:
  format: OGB
  name: ogbg-code2
  task: graph
  task_type: subtoken_prediction
  transductive: False
  node_encoder: True
  node_encoder_name: ASTNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: ASTEdge
  edge_encoder_bn: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: ogb_code_graph
  layer_type: gine
  layers_mp: 4
  layers_pre_mp: 0
  layers_post_mp: 3
  dim_inner: 512
  batchnorm: True
  act: relu
  dropout: 0.1
  agg: mean
  normalize_adj: False
  ffn: True
  residual: True
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-6
  base_lr: 0.0001
  max_epoch: 30
  scheduler: cosine_with_warmup
  num_warmup_epochs: 2
