out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: False
  project: peptides-struct
dataset:
  format: OGB
  name: peptides-structural
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,33)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
  eval_smoothing_metrics: False
model:
  type: custom_gnn
  loss_fun: l1
  graph_pooling: mean
gnn:
  head: mlp_graph
  ffn: False
  layers_pre_mp: 0
  layers_mp: 5
  layers_post_mp: 3
  dim_inner: 200
  layer_type: gine
  act: gelu
  residual: True
  dropout: 0.2
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 250
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
