out_dir: results
metric_best: f1
wandb:
  use: False
  project: Pascal
dataset:
  format: PyG-VOCSuperpixels
  name: edge_wt_region_boundary
  slic_compactness: 30
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: VOCNode+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: VOCEdge
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,33)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
  eval_smoothing_metrics: True
model:
  type: custom_gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: inductive_node
  ffn: False
  layers_pre_mp: 0
  layers_mp: 12
  layers_post_mp: 1
  dim_inner: 95
  layer_type: gatedgcn
  act: gelu
  residual: True
  dropout: 0.15
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
